theme = "solarized_dark"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"

[keys.normal]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
